

services:
  backend:
    build: ./backend        # Don't include the port here, it will be set in the Dockerfile. This prevents the backend from being accessible from outside the container.
        
    environment:
      - PYTHONUNBUFFERED=1  # Ensures that Python output is sent straight to the terminal without buffering
    networks:
      - finnet
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - finnet
    restart: unless-stopped

networks:
  finnet:
    driver: bridge