

services:
  backend:
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - finnet
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:8000  # Needed if frontend calls backend directly (e.g., via API)
    networks:
      - finnet
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Public port (single URL)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Reverse proxy config
    depends_on:
      - backend
      - frontend
    networks:
      - finnet

networks:
  finnet:
    driver: bridge